mongodb:
  host: "172.26.41.150"
  port: 27017
  username: "admin"
  password: "MSvauy7s"
  auth_db: "admin"
  db_name: "heartBeat"

settings:
  total_runtime: 3600
  timeout: 300
  check_interval: 60
  motion_threshold: 0.95
