January:
  - name: "New Year's Day"
    date: "2025-01-01"
  - name: "Republic Day"
    date: "2025-01-27"

February:
  - name: "MahaShivratri"
    date: "2025-02-26"

March:
  - name: "Holi"
    date: "2025-03-14"
  - name: "Eid al Fitr"
    date: "2025-03-31"

April:
  - name: "Gudi Padwa"
    date: "2025-04-01"
  - name: "Good Friday"
    date: "2025-04-18"

May:
  - name: "Maharashtra Day"
    date: "2025-05-01"

June:
  - name: "Eid al Adha"
    date: "2025-06-06"

August:
  - name: "Independence Day"
    date: "2025-08-15"
  - name: "Janmashtami"
    date: "2025-08-18"
  - name: "Ganesh Chaturthi"
    date: "2025-08-27"

October:
  - name: "Gandhi Jayanti"
    date: "2025-10-02"
  - name: "Dussera"
    date: "2025-10-03"

November:
  - name: "Diwali"
    date: "2025-11-21"
  - name: "Bhai Dooj"
    date: "2025-11-23"

December:
  - name: "Christmas"
    date: "2025-12-25"
  - name: "Year End Holiday"
    date: "2025-12-31"
